### ISSUE TITLE
exportSession.exportAsynchronouslyWithCompletionHandler results in AVAssetExportSessionStatus.Failed

### ISSUE THREAD

**Issue by stanchiang** [krezzoid/VideoSliderView-VideoTrimmer#1]
hi i was trying out your code and tapping on trim gave me this error, causing me to get the alert: "Video trimmed - false"

2016-07-24 13:18:38.663 VideoSlider[23257:8753505] This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.

---

btw i'm trying to accomplish something similar in my own project with virtually the same implementation but giving me a different error. have you encountered one this before?

Failed:Optional(Error Domain=AVFoundationErrorDomain Code=-11829 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media may be damaged., NSLocalizedDescription=Cannot Open, NSURL=file:///private/var/mobile/Containers/Data/Application/EE797652-B3F9-4A55-A3B7-DA2A901CB90F/tmp/15.mov, NSUnderlyingError=0x137e37360 {Error Domain=NSOSStatusErrorDomain Code=-12848 "(null)"}})

**Comment by krezzoid** [comment]
hi @stanchiang 

"This media may be damaged" - please make sure that your video file is supported by iOS for playback and file not corrupted.
"This application is modifying the autolayout engine from a background thread" - seems like you are trying to work with UI outside main tread.
At the same time - would be great to see your code sample.
